DROP TABLE IF EXISTS ADDRESSES;
CREATE TABLE ADDRESSES (ID INT AUTO_INCREMENT PRIMARY KEY,
STREET VARCHAR(250) NOT NULL,
NUMBER INT NOT NULL,
LOCATION VARCHAR(250) NOT NULL,
PROVINCE VARCHAR(100) NOT NULL);

DROP TABLE IF EXISTS PATIENTS;
CREATE TABLE PATIENTS (ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
LASTNAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(250) NOT NULL,
CARD_IDENTITY INT NOT NULL,
ADMISSION_OF_DATE DATE NOT NULL,
ADDRESS_ID INT NOT NULL);

DROP TABLE IF EXISTS DENTISTS;
CREATE TABLE DENTISTS (ID INT AUTO_INCREMENT PRIMARY KEY,
REGISTRATION INT NOT NULL,
NAME VARCHAR(100) NOT NULL,
LASTNAME VARCHAR(100) NOT NULL);

INSERT INTO ADDRESSES(STREET, NUMBER, LOCATION, PROVINCE)
VALUES ('Calle A', 101, 'Bella Italia', 'Montevideo');

INSERT INTO PATIENTS (NAME, LASTNAME, EMAIL, CARD_IDENTITY, ADMISSION_OF_DATE, ADDRESS_ID)
VALUES ('Mateo', 'Lopez', 'matelopez2830@gmail.com',53690591, '2025-04-08', 1);

INSERT INTO DENTISTS (REGISTRATION, NAME, LASTNAME)
VALUES (1234, 'Dinar', 'Soria');